name: MMDrawerController
options:
  bundleIdPrefix: com.mutualmobile.mmsdcvc
  deploymentTarget:
    iOS: "8.0"
targets:
  MMDrawerController:
    platform: iOS
    scheme: {} # Generate default scheme
    settings:
      GCC_GENERATE_DEBUGGING_SYMBOLS: NO # Avoid downstream warning: "Redistributable static libraries should never be built with module debugging enabled"
      MACH_O_TYPE: staticlib
      MODULEMAP_FILE: MMDrawerController/MMDrawerController.modulemap
    sources:
      - path: MMDrawerController
        excludes:
          - MMDrawerController.modulemap
    type: framework
